# Generated by Django 6.0.2 on 2026-04-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_alter_categoria_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
