# Generated by Django 6.0.2 on 2026-02-26 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0002_alter_categoria_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('descricao', models.TextField(blank=True, max_length=250)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imagem', models.ImageField(blank=True, upload_to='fotos/produto')),
                ('estoque', models.IntegerField()),
                ('esta_disponivel', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
            ],
        ),
    ]
